remote_theme           : "mmistakes/minimal-mistakes@4.16.4"
minimal_mistakes_skin    : "contrast" # "air"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-data